// flow-typed signature: b55e91a229fec5cc9e3244f4676a3ebb
// flow-typed version: <<STUB>>/bingmaps_v^1.0.13/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bingmaps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bingmaps' {
  declare module.exports: any;
}
