// flow-typed signature: 537aef64c0008e2b6a2185402763f69e
// flow-typed version: <<STUB>>/inline-worker_v^1.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inline-worker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inline-worker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'inline-worker/index' {
  declare module.exports: $Exports<'inline-worker'>;
}
declare module 'inline-worker/index.js' {
  declare module.exports: $Exports<'inline-worker'>;
}
