// flow-typed signature: b0c700446a739f2871715bbfb5287cd3
// flow-typed version: <<STUB>>/mapzen.js_v^0.6.3/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapzen.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapzen.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mapzen.js/src/js/components/apiKeyCheck' {
  declare module.exports: any;
}

declare module 'mapzen.js/src/js/components/basemapStyles' {
  declare module.exports: any;
}

declare module 'mapzen.js/src/js/components/hash' {
  declare module.exports: any;
}

declare module 'mapzen.js/src/js/components/locator' {
  declare module.exports: any;
}

declare module 'mapzen.js/src/js/components/mapControl' {
  declare module.exports: any;
}

declare module 'mapzen.js/src/js/components/search' {
  declare module.exports: any;
}

declare module 'mapzen.js/src/js/components/tangram' {
  declare module.exports: any;
}

declare module 'mapzen.js/src/js/mapzen' {
  declare module.exports: any;
}

declare module 'mapzen.js/test/karma.conf' {
  declare module.exports: any;
}

declare module 'mapzen.js/test/spec/hash' {
  declare module.exports: any;
}

declare module 'mapzen.js/test/spec/mapControl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mapzen.js/src/js/components/apiKeyCheck.js' {
  declare module.exports: $Exports<'mapzen.js/src/js/components/apiKeyCheck'>;
}
declare module 'mapzen.js/src/js/components/basemapStyles.js' {
  declare module.exports: $Exports<'mapzen.js/src/js/components/basemapStyles'>;
}
declare module 'mapzen.js/src/js/components/hash.js' {
  declare module.exports: $Exports<'mapzen.js/src/js/components/hash'>;
}
declare module 'mapzen.js/src/js/components/locator.js' {
  declare module.exports: $Exports<'mapzen.js/src/js/components/locator'>;
}
declare module 'mapzen.js/src/js/components/mapControl.js' {
  declare module.exports: $Exports<'mapzen.js/src/js/components/mapControl'>;
}
declare module 'mapzen.js/src/js/components/search.js' {
  declare module.exports: $Exports<'mapzen.js/src/js/components/search'>;
}
declare module 'mapzen.js/src/js/components/tangram.js' {
  declare module.exports: $Exports<'mapzen.js/src/js/components/tangram'>;
}
declare module 'mapzen.js/src/js/mapzen.js' {
  declare module.exports: $Exports<'mapzen.js/src/js/mapzen'>;
}
declare module 'mapzen.js/test/karma.conf.js' {
  declare module.exports: $Exports<'mapzen.js/test/karma.conf'>;
}
declare module 'mapzen.js/test/spec/hash.js' {
  declare module.exports: $Exports<'mapzen.js/test/spec/hash'>;
}
declare module 'mapzen.js/test/spec/mapControl.js' {
  declare module.exports: $Exports<'mapzen.js/test/spec/mapControl'>;
}
