// flow-typed signature: 2ffd3c5285d5d793bf7e56bed6ab180b
// flow-typed version: <<STUB>>/mojs_v^0.2.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mojs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mojs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mojs/demo/output/destructuring' {
  declare module.exports: any;
}

declare module 'mojs/demo/output/lambdas' {
  declare module.exports: any;
}

declare module 'mojs/demo/output/lc' {
  declare module.exports: any;
}

declare module 'mojs/demo/output/this' {
  declare module.exports: any;
}

declare module 'mojs/lib/mojs' {
  declare module.exports: any;
}

declare module 'mojs/lib/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mojs/demo/output/destructuring.js' {
  declare module.exports: $Exports<'mojs/demo/output/destructuring'>;
}
declare module 'mojs/demo/output/lambdas.js' {
  declare module.exports: $Exports<'mojs/demo/output/lambdas'>;
}
declare module 'mojs/demo/output/lc.js' {
  declare module.exports: $Exports<'mojs/demo/output/lc'>;
}
declare module 'mojs/demo/output/this.js' {
  declare module.exports: $Exports<'mojs/demo/output/this'>;
}
declare module 'mojs/lib/mojs.js' {
  declare module.exports: $Exports<'mojs/lib/mojs'>;
}
declare module 'mojs/lib/tests.js' {
  declare module.exports: $Exports<'mojs/lib/tests'>;
}
