// flow-typed signature: c22382752426cb98d4954bddf6935f47
// flow-typed version: <<STUB>>/nosleep_vBHSPitMonkey/NoSleep.js/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nosleep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nosleep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'nosleep/index' {
  declare module.exports: $Exports<'nosleep'>;
}
declare module 'nosleep/index.js' {
  declare module.exports: $Exports<'nosleep'>;
}
