const FETCHING_PATTERNS = 'FETCHING_PATTERNS'
const FETCHING_PATTERNS_ERROR = 'FETCHING_PATTERNS_ERROR'
const FETCHING_PATTERNS_SUCCESS = 'FETCHING_PATTERNS_SUCCESS'

const ADD_PATTERN = 'ADD_PATTERN'