const FETCHING_PROPOSALS = 'FETCHING_PROPOSALS'
const FETCHING_PROPOSALS_ERROR = 'FETCHING_PROPOSALS_ERROR'
const FETCHING_PROPOSALS_SUCCESS = 'FETCHING_PROPOSALS_SUCCESS'

const ADD_PROPOSAL = 'ADD_PROPOSAL'