const FETCHING_QUESTIONS = 'FETCHING_QUESTIONS'
const FETCHING_QUESTIONS_ERROR = 'FETCHING_QUESTIONS_ERROR'
const FETCHING_QUESTIONS_SUCCESS = 'FETCHING_QUESTIONS_SUCCESS'

const ADD_QUESTION = 'ADD_QUESTION'