const FETCHING_RESPONSES = 'FETCHING_RESPONSES'
const FETCHING_RESPONSES_ERROR = 'FETCHING_RESPONSES_ERROR'
const FETCHING_RESPONSES_SUCCESS = 'FETCHING_RESPONSES_SUCCESS'

const ADD_RESPONSE = 'ADD_RESPONSE'