const FETCHING_USER_PROPOSALS = 'FETCHING_USER_PROPOSALS'
const FETCHING_USER_PROPOSALS_ERROR = 'FETCHING_USER_PROPOSALS_ERROR'
const FETCHING_USER_PROPOSALS_SUCCESS = 'FETCHING_USER_PROPOSALS_SUCCESS'

const ADD_USER_PROPOSAL = 'ADD_USER_PROPOSAL'