const FETCHING_USER_COMMUTES = 'FETCHING_USER_COMMUTES'
const FETCHING_USER_COMMUTES_ERROR = 'FETCHING_USER_COMMUTES_ERROR'
const FETCHING_USER_COMMUTES_SUCCESS = 'FETCHING_USER_COMMUTES_SUCCESS'

const ADD_USER_COMMUTE = 'ADD_USER_COMMUTE'