const FETCHING_USER_RESPONSES = 'FETCHING_USER_RESPONSES'
const FETCHING_USER_RESPONSES_ERROR = 'FETCHING_USER_RESPONSES_ERROR'
const FETCHING_USER_RESPONSES_SUCCESS = 'FETCHING_USER_RESPONSES_SUCCESS'

const ADD_USER_RESPONSE = 'ADD_USER_RESPONSE'